### PR TITLE
Tidy2

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by martyall** [comment]
I don't want to sound discouraging, I really appreciate the work you're putting in and that you're interested in these projects. But honestly there is pretty much no way I'm going to be able to look at a PR like this. We don't have an official guide for how to make PRs, but IMO there are some basic rules that should be followed for all PRs on any open source project in order to better ensure sure upgrade paths are easy and releases always work:

1. Clearly state a summary of the problem that the PR addresses, specifically by linking to an issue which has already been filed.

2. Files that don't actually contain changes should not be included. For example, if your editor automatically introduces white space or something like this compared to the reference files, it should not be included. Also if files are listed explicitly in the `.gitignore` file, we should keep them ignored without good reason (e.g. all of the generated purescript modules for the test suite)

3. PRs that are hundreds to thousands of lines of additions should be meaningful, like major features or planned refactors. If you are just including a bunch of small changes that you think are improvements, those improvements need to be bundled and detailed in some issue somewhere.

4. In general, do not change filenames of modules in the library without a good reason. It creates a problem for downstream dependencies that is not worth the hassle. Arguable this rule should hold for test files as well. 

I understand this is a work in progress, but I just want to make the above points so we're on the same page. These rules should hold for the other PRs you're making across the other Web3 repositories. Again, I think you're doing great work, but we just need to make things more uniform and transparent. Thanks!

**Comment by srghma** [comment]
hi @martyall I have seen Your comment

> Clearly state a summary of the problem that the PR addresses

no summary, I'm just learning the lib

> if your editor automatically introduces white space

my editor doesnt introduce new spaces (though it can add a trailing newline at the end of the file), instead it removes the trailing whitespace (which I have seen exists)

You don't want me to include these changes?

> Also if files are listed explicitly in the .gitignore file, we should keep them ignored without good reason

I have added `./contracts`, to see how changes to the generator change contracts

I would also do https://github.com/purescript-graphqlclient/purescript-graphqlclient/blob/fb4497e7e5c8f5cc7a7aad6ac4d8585737f91a3f/ci-approve.sh#L12-L23

> PRs that are hundreds to thousands of lines of additions should be meaningful, like major features or planned refactors. If you are just including a bunch of small changes that you think are improvements, those improvements need to be bundled and detailed in some issue somewhere

ok, but it's hard to make an issue  `to add comments that explain functions for newcomers` before the change is introduced, I'm just learning

> In general, do not change filenames of modules in the library without a good reason

I think the reason is good, the `Data` is not the right module name

> It creates a problem for downstream dependencies that is not worth the hassle

I will sync all libs myself

> Arguable this rule should hold for test files as well

I dont remember that I have changed `module Test.Main` to something else, only moved file from `./test/Main.purs` to `./test/Test/Main.purs` (using the program https://github.com/srghma/update-module-name-purs), b.c. haskell language for example enforces that module name is eq to path to the file (also easier to navigate)

Summary: You guys have created an amazing lib, and I'm just learning it

and will continue to learn

I cannot see how I right now will change my behavior to `oh, god, they don't like that there are so much small changes, I should now revise every comment I have maid and think about "would they like change X or no"`

I also won't ask about each change "can I make it or no" - I will continue just making them and will ask sorry later, that's just easier

Sorry If I sound angry, I am not, but on other hand such an attitude just stifles any action forward

I dont know what You expect me to do

Maybe let's have a call after I update foam.tcr and think together what changes to leave and what to dismiss?

**Comment by martyall** [comment]
If you are just learning the library and making changes on your local branch, that's up to you. But then I would ask why would you open a PR? Just learn the library on your own, file some issue under "Pain points for newcomers" that highlights the problems you encountered that you wish were different, then maintainers of the library will have a chance to discuss this issue with you, then open a PR that reflects that discussion. 

> I cannot see how I right now will change my behavior to oh, god, they don't like that there are so much small changes, I should now revise every comment I have maid and think about "would they like change X or no"

> I also won't ask about each change "can I make it or no" - I will continue just making them and will ask sorry later, that's just easier

Whatever you want to do on your own fork is your business. The development cycle we use _here in these projects_ is not some custom thing that we made up -- it's the same development cycle that gets used everywhere for open source projects used/maintained by multiple people, not all with the same goals or projects in mind. 

1. Issue gets filed
2. Discussion happens on that issue
3. PR gets made to address issues
4. PR gets reviewed with possible changes
5. PR gets merged to master
6. Releases get made from a group of merged PRs

**Comment by srghma** [comment]
done

I thought Your comment was about `I don't want to see this, remove`, but now I see that it's about `split on issues and let's discuss`

**Pull request closed without merging**
